# Generated by Django 5.1 on 2024-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True)),
                ('task_name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('influencer', models.CharField(max_length=255)),
                ('artist_agreed', models.BooleanField(default=False)),
                ('influencer_agreed', models.BooleanField(default=False)),
            ],
        ),
    ]
