# Generated by Django 5.1 on 2024-08-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_roomcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True)),
                ('artist', models.CharField(max_length=255)),
                ('influencer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='task',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.channel'),
        ),
    ]
