# Generated by Django 5.1 on 2024-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_channel_remove_task_artist_remove_task_influencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
