# Generated by Django 5.1 on 2024-08-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='artist_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='influencer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
